-- 产品
DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
  PRODUCT_ID      INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
  PRODUCT_NAME    VARCHAR(100) NOT NULL,
  PRODUCT_TOTAL   INT          NOT NULL,
  PRODUCT_SOLD    INT          NOT NULL,
  PRODUCT_VERSION INT
);

-- 订单
DROP TABLE IF EXISTS SALE_ORDER;
CREATE TABLE SALE_ORDER (
  ORDER_ID    INT             NOT NULL PRIMARY KEY AUTO_INCREMENT,
  PRODUCT_ID  INT             NOT NULL,
  ORDER_NAME  VARCHAR(100)    NOT NULL,
  CREATE_TIME LONGVARCHAR(20) NOT NULL
);
