-- 产品
DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
  PRODUCT_ID      INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
  -- 产品名称
  PRODUCT_NAME    VARCHAR(100) NOT NULL,
  -- 总数
  PRODUCT_TOTAL   INT          NOT NULL,
  -- 已购数
  PRODUCT_SOLD    INT          NOT NULL,
  PRODUCT_VERSION INT
);

-- 分表:根据PRODUCT_ID进行分表，哈希PRODUCT_ID

-- 订单
DROP TABLE IF EXISTS SALE_ORDER_0;
CREATE TABLE SALE_ORDER_0 (
  ORDER_ID    INT             NOT NULL PRIMARY KEY AUTO_INCREMENT,
  -- 产品
  PRODUCT_ID  INT             NOT NULL,
  -- 订单名称
  ORDER_NAME  VARCHAR(100)    NOT NULL,
  CREATE_TIME LONGVARCHAR(20) NOT NULL
);

-- 订单
DROP TABLE IF EXISTS SALE_ORDER_1;
CREATE TABLE SALE_ORDER_1 (
  ORDER_ID    INT             NOT NULL PRIMARY KEY AUTO_INCREMENT,
  -- 产品
  PRODUCT_ID  INT             NOT NULL,
  -- 订单名称
  ORDER_NAME  VARCHAR(100)    NOT NULL,
  CREATE_TIME LONGVARCHAR(20) NOT NULL
);

-- 订单
DROP TABLE IF EXISTS SALE_ORDER_2;
CREATE TABLE SALE_ORDER_2 (
  ORDER_ID    INT             NOT NULL PRIMARY KEY AUTO_INCREMENT,
  -- 产品
  PRODUCT_ID  INT             NOT NULL,
  -- 订单名称
  ORDER_NAME  VARCHAR(100)    NOT NULL,
  CREATE_TIME LONGVARCHAR(20) NOT NULL
);
